spring.application.name=url-shortener
server.port=8080

spring.datasource.url=jdbc:h2:mem:urlshortener
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.h2.console.enabled=true

app.frontend-origin=https://url-shortner-ten-red.vercel.app
app.backend-base-url=https://url-shortner-webapp.onrender.com
